"""Generate the shipped review workflow without loading personal settings."""

from __future__ import annotations

import argparse
from copy import deepcopy
from dataclasses import asdict
from html import escape
from pathlib import Path
import sys
from tempfile import TemporaryDirectory

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "plugins/review-suite/scripts"))

from review_suite_core.config import _job_model, load_config
from review_suite_core.orchestrator_profiles import (
    SUPPORTED_MODES,
    load_orchestrator_profiles,
)
from review_suite_core.orchestrator_state import (
    _github_review_required,
    deslop_should_run,
)


def model_label(model: str, effort: str, tier: str | None = None) -> str:
    model = {"gpt-6-astra": "Astra"}.get(model, model)
    return escape(" / ".join(part for part in (model, effort, tier) if part))


def render(config: dict) -> str:
    config = deepcopy(config)
    arena_default = "enabled" if config["arena"]["enabled"] else "disabled"
    # Show the optional Arena branch even when the shipped default disables it.
    config["arena"]["enabled"] = True
    profiles = load_orchestrator_profiles(config)["stable"]
    cleanup = _job_model(config, "deslop")
    cleanup_label = model_label(
        cleanup["model"], cleanup["reasoning_effort"], cleanup["service_tier"]
    )
    lines = [
        "# Review workflow",
        "",
        "<!-- Generated by scripts/generate-workflow.py; do not edit by hand. -->",
        "",
        "Shipped defaults, without personal overrides. Arena is optional and "
        f"**{arena_default} by default**; its configured loops are shown below.",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for mode in SUPPORTED_MODES:
        steps = profiles[mode].steps
        state = {
            "stage": "created",
            "mode": {"effective": mode},
            "deslop": {"tracked": True, "status": "tracked"},
            "review_plan": {"steps": [asdict(step) for step in steps]},
        }
        labels = []
        index = 0
        while index < len(steps):
            state["review_progress"] = {"next_step_index": index}
            if deslop_should_run(state):
                labels.append(f"Cleanup once<br/>{cleanup_label}")
            step = steps[index]
            if step.kind == "arena":
                end = index + 1
                while (
                    end < len(steps)
                    and steps[end].kind == "arena"
                    and steps[end].rating_pool_id == step.rating_pool_id
                ):
                    end += 1
                labels.append(
                    f"Optional Arena<br/>{len(step.variant_ids)} variants / {end - index} loops"
                )
                index = end
            else:
                label = model_label(
                    step.model, step.reasoning_effort, step.service_tier
                )
                title = "Final signoff" if index == len(steps) - 1 else "Review"
                labels.append(f"{title}<br/>{step.count} reviewers / {label}")
                index += 1
        if _github_review_required(state):
            labels.append("GitHub review<br/>Service-selected model")
        labels.append("Done")
        lines.append(f'  subgraph {mode}["{mode}"]')
        for index, label in enumerate(labels):
            lines.append(f'    {mode}_{index}["{label}"]')
        lines.append(
            "    " + " --> ".join(f"{mode}_{index}" for index in range(len(labels)))
        )
        lines.append("  end")
    lines.extend(
        [
            "```",
            "",
            "Reviewers report findings; fixes are reviewed before advancing. Cleanup "
            "runs once before final signoff and does not repeat after later fixes. "
            "Required validation must pass before completion.",
            "",
            "Regenerate with `uv run --locked python scripts/generate-workflow.py`. "
            "CI runs the same command with `--check` to catch stale output.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail if the committed diagram is stale."
    )
    args = parser.parse_args()
    with TemporaryDirectory() as directory:
        content = render(load_config(Path(directory)))
    output = ROOT / "docs/review-workflow.md"
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != content:
            print(
                "Workflow is stale. Run: uv run --locked python scripts/generate-workflow.py",
                file=sys.stderr,
            )
            return 1
        print("workflow: current")
    else:
        output.write_text(content, encoding="utf-8", newline="\n")
        print("generated: docs/review-workflow.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
